name: McPanel
main: com.example.mcpanel.MainPlugin
version: 1.0.0
api-version: 1.19
author: 3godziny
description: Paper 1.19.2 plugin with web admin panel in Kotlin/Ktor

commands:
  start:
    description: Inicjalizacja panelu i plików konfiguracyjnych
    usage: /start
    permission: op
  rangi:
    description: Wyświetla listę rang
    usage: /rangi
  staty:
    description: Wyświetla statystyki gracza
    usage: /staty
  ranganadaj:
    description: Ustawia rangę graczowi
    usage: /ranganadaj <nick> <ranga>
    permission: op
  rangausun:
    description: Usuwa wskazaną rangę graczowi (reset do default)
    usage: /rangausun <nick> <ranga>
    permission: op
  helpop:
    description: Wyślij prośbę do administracji
    usage: /helpop <wiadomość>
  anshelpop:
    description: Odpowiedź na helpop
    usage: /anshelpop <nick> <wiadomość>
    permission: mcpanel.anshelpop
  war:
    description: Wyślij ostrzeżenie (czarny ekran) graczowi
    usage: /war <nick> <wiadomość>
    permission: mcpanel.war
  mcpanel:
    description: Zarządzanie pluginem McPanel
    usage: /mcpanel <reload|status>
